apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: validador-tamaprint
  labels:
    cloud.googleapis.com/location: us-central1
    run.googleapis.com/cpu-throttling: 'true'
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      labels:
        run.googleapis.com/startupProbeType: Default
      annotations:
        autoscaling.knative.dev/maxScale: '10'
        autoscaling.knative.dev/minScale: '0'
        run.googleapis.com/cpu-throttling: 'true'
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - name: validador-tamaprint-container
        image: gcr.io/PROJECT_ID/validador-tamaprint
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: PORT
          value: '8080'
        - name: ENVIRONMENT
          value: 'production'
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: '/app/credentials.json'
        # Estas variables se configurarán manualmente en Cloud Run Console:
        # - name: GOOGLE_DRIVE_FILE_ID
        #   value: 'tu_file_id_aquí'
        # - name: GOOGLE_SHEET_RANGE  
        #   value: 'Hoja1!A1:Z1000'
        resources:
          limits:
            cpu: '1'
            memory: 512Mi
          requests:
            cpu: '1'
            memory: 512Mi
        volumeMounts:
        - name: google-sheets-credentials
          mountPath: /app
          readOnly: true
        startupProbe:
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 1
          tcpSocket:
            port: 8080
      volumes:
      - name: google-sheets-credentials
        secret:
          secretName: google-sheets-credentials
          items:
          - key: latest
            path: credentials.json
  traffic:
  - percent: 100
    latestRevision: true